export let config = {
    "token": "NTk2NTAyNzkwNjI1NTU4NTU4.XR6oSg.I8NB6I5cKXsU1vG-lCIfdT9gxMs",
    "prefix": "!",
    "commands": [
        //"play",
        "leave",
        "kick",
        "ban",
        "purge",
        "profroles",
        "warrior",
        "warlock",
        "rogue",
        "priest",
        "paladin",
        "mage",
        "hunter",
        "druid",
        "healer",
        "tank",
        "ranged",
        "melee",
        "stats",
        "serverinfo",
        "help",
        "getroles",
        "meme",
        "cat",
        "dog",
        "random",
        "simmer"
    ], 
    "badWords": [
        "nigger",
        "nigga",
        "chink",
        "faggot",
        "cunt",
    ]
}