export let config = {
    "token": "",
    "prefix": "!",
    "commands": [
        //"play",
        "leave",
        "kick",
        "ban",
        "purge",
        "profroles",
        "warrior",
        "warlock",
        "rogue",
        "priest",
        "paladin",
        "mage",
        "hunter",
        "druid",
        "healer",
        "tank",
        "ranged",
        "melee",
        "stats",
        "serverinfo",
        "help",
        "getroles",
        "meme",
        "cat",
        "dog",
        "random",
        "simmer"
    ], 
    "badWords": [
    ]
}
